"""replace date field with datetime field

Revision ID: 6df1497000d7
Revises: 25225257f761
Create Date: 2025-03-11 16:19:38.805757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6df1497000d7"
down_revision: Union[str, None] = "25225257f761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("date_time", sa.DateTime(), nullable=True))
    op.execute("UPDATE documents SET date_time = date")
    op.drop_column("documents", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("date", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.execute("UPDATE documents SET date = date_time::date")
    op.drop_column("documents", "date_time")
    # ### end Alembic commands ###
