"""change total chunks to session id

Revision ID: 983d52dade33
Revises: 6df1497000d7
Create Date: 2025-03-14 16:20:19.480455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "983d52dade33"
down_revision: Union[str, None] = "6df1497000d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add session_id column as nullable initially
    op.add_column("documents", sa.Column("session_id", sa.Integer(), nullable=True))

    # Copy data from total_chunks to session_id
    op.execute("UPDATE documents SET session_id = total_chunks")

    # Make session_id non-nullable
    op.alter_column("documents", "session_id", nullable=False)

    # Drop the old column
    op.drop_column("documents", "total_chunks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("total_chunks", sa.INTEGER(), autoincrement=False, nullable=True),
    )

    # Copy data back
    op.execute("UPDATE documents SET total_chunks = session_id")

    # Make total_chunks non-nullable
    op.alter_column("documents", "total_chunks", nullable=False)

    # Drop the new column
    op.drop_column("documents", "session_id")
    # ### end Alembic commands ###
